---
minecraft:ghast_tear:
  effects:
    speed:
    - 1 # L'ID de l'effet
    - 20 # La durée de l'effet
    - 3 # Le niveau de l'effet
    - false # True pour afficher les particules, false pour les cacher
  time: 10 
  use: 5
popup: '§bCooldown: §c{time}'
use: '§bUtilisation: §e{use}'
...